ALTER TABLE exam_target_rules
DROP CONSTRAINT IF EXISTS exam_target_rules_target_type_check;

ALTER TABLE exam_target_rules
DROP COLUMN IF EXISTS target_type,
DROP COLUMN IF EXISTS target_value,
ADD COLUMN IF NOT EXISTS class_id INT REFERENCES classes(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS grade_level VARCHAR(10),
ADD COLUMN IF NOT EXISTS major_code VARCHAR(20),
ADD COLUMN IF NOT EXISTS religion VARCHAR(50);
