ALTER TABLE exam_target_rules
DROP COLUMN IF EXISTS class_id,
DROP COLUMN IF EXISTS grade_level,
DROP COLUMN IF EXISTS major_code,
DROP COLUMN IF EXISTS religion,
ADD COLUMN IF NOT EXISTS target_type VARCHAR(10) NOT NULL DEFAULT 'CLASS',
ADD COLUMN IF NOT EXISTS target_value VARCHAR(50) NOT NULL DEFAULT '';
